
INSERT INTO PROJECT VALUES (1, 'Admin', CURRENT_TIMESTAMP, 3, 'AdarshCrystal');
INSERT INTO PROJECT VALUES (2, 'Admin', CURRENT_TIMESTAMP, 5, 'BearysTriangle');

INSERT INTO FLOOR VALUES (1,'Ground Floor', 1);
INSERT INTO FLOOR VALUES (2,'First Floor', 1);
INSERT INTO FLOOR VALUES (3,'Second Floor', 1);


INSERT INTO AREA VALUES (1,'Main Entrance', 1);
INSERT INTO AREA VALUES (2,'Hampi', 1);
INSERT INTO AREA VALUES (3,'Jogfalls', 1);

INSERT INTO ASSET VALUES (1,'Diffuser',1);
INSERT INTO ASSET VALUES (2,'Detector',1);
INSERT INTO ASSET VALUES (3,'Light Fixture',1);
INSERT INTO ASSET VALUES (4,'Projector',2);
INSERT INTO ASSET VALUES (5,'Light Fixture',2);
INSERT INTO ASSET VALUES (6,'Table',2);
INSERT INTO ASSET VALUES (7,'TV1',3);
INSERT INTO ASSET VALUES (8,'TV2',3);
INSERT INTO ASSET VALUES (9,'Light Fixture',3);

INSERT INTO DOCUMENT VALUES (1,'Admin',CURRENT_TIMESTAMP ,'AC - Certificate.pdf','Certificate',1);
INSERT INTO DOCUMENT VALUES (2,'Admin',CURRENT_TIMESTAMP ,'AC - UserManual.pdf','UserManual',1);
INSERT INTO DOCUMENT VALUES (3,'Admin',CURRENT_TIMESTAMP ,'AC - Specification.pdf','Specification',1);
INSERT INTO DOCUMENT VALUES (4,'Admin',CURRENT_TIMESTAMP ,'AC - Warranty.pdf','Warranty',1);


